# .github/workflows/release.yml

name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'  # 只有以 v 开头的 tag（如 v1.0.0）才会触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Libs
      uses: actions/checkout@v4
    
    - name: Generate SHA256 Hash
      run: |
        cd releases
        sha256sum * > ../sha256sums.txt
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          releases/*
          sha256sums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
